---
title: "p8105_hw5_kp3127"
output: html_document
date: "2025-11-05"
---
```{r setup, echo=FALSE}
library(tidyverse)
library(rvest)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
set.seed(1)
```

# Problem 1
Write a function to check whether there are duplicate birthdays in the group
```{r}
bd_check <- function(n, days = 365) {
  bdays <- sample.int(days, size = n, replace = TRUE)
  any(duplicated(bdays))
}
```

Compute the probability for each group size between 2 and 50, running 10000 times:
```{r}
sim_df=
  tibble(gp_size=2:50) %>% 
  mutate(prob=map_dbl(.x=gp_size,~mean(replicate(10000,bd_check(.x)))))
```

```{r}
sim_df |>
  ggplot(aes(x = gp_size, y = prob)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = 2) +
  labs(
    title = "Birthday problem: Pr(≥2 share a birthday) vs group size",
    x = "Group size (n)",
    y = "Estimated probability (10,000 sims per n)"
  ) +
  theme_minimal()
```
The curve rises monotonically with group size. It crosses 0.50 when n = 23.  
This result matches the classic birthday paradox: with just 23 people, there’s over a 50% chance at least two share a birthday.
